# Generated by Django 3.0.3 on 2020-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=24)),
                ('status_style', models.CharField(max_length=8)),
                ('status_icon', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(db_column='model_id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=64)),
                ('model_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('model_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(db_column='ticket_id', primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=48)),
                ('client_phone', models.CharField(blank=True, max_length=18, null=True)),
                ('imei', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ожидает'), (10, 'В ремонте'), (20, 'Повторно'), (30, 'Согласовать'), (35, 'Согласовано'), (40, 'Ждет запчасти'), (50, 'Готов'), (80, 'Отказ'), (99, 'Выданные')], verbose_name='Status')),
                ('date_create', models.DateTimeField()),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
